name: .NET Framework Build

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Restore NuGet packages
      run: nuget restore HDT-Reconnector.sln

    - name: Build project
      run: msbuild HDT-Reconnector.sln /p:Configuration=Release

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          **/*.dll
          **/*.exe
          **/*.pdb
          **/*.config
